CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number VARCHAR(255) DEFAULT NULL,
    sku_code     VARCHAR(255),
    price        DECIMAL,
    quantity     INTEGER,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);