spring.application.name=order-service
spring.datasource.url=jdbc:postgres://localhost:5433/mydatabase
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
server.port=8081